/*
 * PES Project Four Functions Enum List Header Code
 * Tristan Duenas
 * References:
 */

#ifndef __FUNCTION_NAMES_H__
#define __FUNCTION_NAMES_H__

#include <string.h>

#define MAX_NAME_LENGTH 100

typedef enum function_names
{
	// Color Sensor Control
	COLOR_SENSOR_INIT = 0,
	COLOR_SENSOR_POST_TEST = 1,
	GET_COLOR_SENSOR_REGISTER_VALUE = 2,
	// I2C Control
	I2C_WAIT = 3,
	I2C_TRANSMIT = 4,
	// LED Control
	LED_CONTROL = 5,
	// State Machine Control
	RUN_STATE_MACHINES = 6,
	RUN_STATE_MACHINE_ONE = 7,
	RUN_STATE_MACHINE_TWO = 8,
	// Time Control
	DELAY = 9,
	MAIN = 10,
	// UART Control
	UART_0_INIT = 11,
	UART_0_TRANSMITTER_AVAILABLE = 12,
	UART_0_TRANSMIT_CHARACTER = 13,
	UART_0_POLLING_TRANSMIT_CHARACTER_ON_AVAILABILITY = 14,
	UART_0_RECEIVER_CHARACTER_AVAILABLE = 15,
	UART_0_RECEIVE_CHARACTER = 16,
	UART_0_RECEIVE_CHARACTER_ON_AVAILABILITY = 17,
	UART_0_POLLING_ECHO_CHARACTER = 18,
	UART_0_IRQ_HANDLER = 19,
	UART_0_INTERRUPT_TRANSMIT_CHARACTER_ON_AVAILABILITY = 20,
	UART_0_INTERRUPT_RECEIVE_CHARACTER_ON_AVAILABILITY = 21,
	UART_0_INTERRUPT_CHECK_ERRORS = 22,
	UART_0_INTERRUPT_ECHO_CHARACTERS = 23,
	// Circular Buffer
	INITIALIZE_BUFFER = 24,
	ADD_ITEM = 25,
	REMOVE_ITEM = 26,
	CHECK_IF_BUFFER_IS_FULL = 27,
	CHECK_IF_BUFFER_IS_EMPTY = 28,
	CHECK_IF_BUFFER_IS_INITIALIZED = 29,
	CHECK_IF_BUFFER_POINTER_IS_VALID = 30,
	// Application Mode
	APPLICATION_INIT = 31,
	PROCESS_AND_DISPLAY_RECEIVED_CHARACTERS = 32,
	UPDATE_ASCII_TRACKER = 33,
	DISPLAY_ASCII_TRACKER = 34,
	// DAC
	DAC_CALL_BACK = 35,
	ADC_CALL_BACK = 36,
	DMA_TRANSFER = 37,
	DSP_PROCESS_REPORT = 38,
} Function_Names;

void getFunctionName(Function_Names function, char* name);

#endif
